// Copyright (c) 2026 Fox Council - VintageHive - https://github.com/FoxCouncil/VintageHive

using System.Security.Cryptography;

namespace VintageHive.Proxy.Yahoo;

// Server-side implementation of the YMSG v9 "0x0b" auth crypt - the one a client runs when the server's AUTH
// packet carries field 13 = "1". The client derives a key from the challenge seed, hashes the password two ways,
// and returns two strings in fields 6 and 96. We compute the same two strings from the stored password and
// compare, which is the only way this server can actually verify a Yahoo login.
//
// This is a faithful port of yahoo_process_auth_0x0b() from bitlbee 1.2.4 protocols/yahoo/libyahoo2.c. It is
// pinned against known-answer vectors generated by compiling and running that C code directly - see
// YmsgCryptTests and Tests/VintageHiveTests/TestData/ymsg-auth-vectors.tsv. Do not "clean up" the odd parts:
// the truncations, the 22-character y64 strings and the SHA-1 length poke below are all load-bearing, and any
// deviation makes real clients fail to authenticate.
internal static class YmsgCrypt
{
    // The seed alphabet. Phase 1 maps each character to 5 bits via this table.
    internal const string ChallengeLookup = "qzec2tb3um1olpar8whx4dfgijknsvy5";

    // ...and each operator to the low 3 bits.
    internal const string OperandLookup = "+|&%/*^-";

    const string Alphabet1 = "FBZDWAGHrJTLMNOPpRSKUVEXYChImkwQ";

    const string Alphabet2 = "F0E1D2C3B4A59687abcdefghijklmnop";

    const string DelimitLookup = ",;";

    // y64 is plain base64 over a different alphabet, with '-' where standard base64 puts '='. Note this string is
    // 65 characters, not 64: the reference indexes [64] for padding, which is the trailing '-'. A 16-byte digest
    // therefore encodes to 24 characters ending "--", and that length is what the XOR pads below consume.
    const string Y64Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-";

    const char Y64Pad = '-';

    // The fixed salt the Yahoo client passes to its MD5-crypt.
    const string CryptSalt = "$1$_2S43d5f$";

    // Phase 3 decodes exactly 20 bytes out of the parsed seed: 4 key bytes plus a 16-byte MD5 to search against.
    // A seed too short to fill all 20 leaves the comparison bytes undefined (literally uninitialised stack in the
    // reference), so we refuse rather than compute something neither side can agree on.
    const int ComparisonLength = 20;

    internal sealed record AuthResponse(string Resp6, string Resp96)
    {
        // Exposed for tests and for logging a refusal without echoing the password.
        internal byte[] MagicKey { get; init; }

        internal int Depth { get; init; }

        internal int Table { get; init; }

        internal int JFinal { get; init; }
    }

    // Everything derivable from the challenge alone. Deriving this runs the client's brute-force search, which is
    // the only expensive part of the whole exchange, so the server does it once when it issues the challenge
    // rather than once per login attempt.
    internal sealed record ChallengeState(byte[] MagicKey, int Depth, int Table, int JFinal);

    // Returns null when the seed cannot be processed the way a real client would process it. Callers must treat
    // null as "cannot verify" and refuse the login - never as "allow".
    internal static ChallengeState PrepareChallenge(string seed)
    {
        if (string.IsNullOrEmpty(seed))
        {
            return null;
        }

        var magic = ParseSeedMagic(seed);

        if (magic == null)
        {
            return null;
        }

        var comparison = BuildComparisonSource(magic);

        if (comparison == null)
        {
            return null;
        }

        var magicKey = new byte[4];

        Array.Copy(comparison, magicKey, 4);

        // The client brute-forces the (depth, table) pair whose MD5 matches the tail of the comparison block.
        // That match is not a checksum nicety: it is how a real server told the client which yahoo_fn.c transform
        // to run on the key, and a real client refuses to answer a seed whose search never matches. Our crafted
        // seeds embed (depth 0, table 0), so the search succeeds on the client's very first candidate.
        var (depth, table, jFinal, found) = SearchTransformTable(magicKey, comparison);

        if (found && depth != 0)
        {
            // A nonzero depth would send the key through yahoo_fn.c's 4600-line permutation table, which we
            // deliberately do not carry. Our own seeds always encode depth 0, so reaching this means either a
            // truncated-MD5 collision (odds around 2^-108) or someone replaying a captured real-server seed at
            // us. Fail closed rather than compute an answer the client will not.
            return null;
        }

        // depth == 0 makes yahoo_xfrm() an identity function (its loop body never runs), so the key is unchanged.
        // The not-found fallthrough (depth 0 / table 0 / j 5) is kept for the legacy random seeds the pinned
        // vectors cover - the reference computes exactly that when nothing matches.
        return new ChallengeState(magicKey, depth, table, jFinal);
    }

    internal static AuthResponse ComputeResponses(ChallengeState state, string password)
    {
        if (state == null || password == null)
        {
            return null;
        }

        var passwordHash = Y64(MD5.HashData(Encoding.UTF8.GetBytes(password)));

        var cryptHash = Y64(MD5.HashData(Encoding.UTF8.GetBytes(YahooCrypt(password, CryptSalt))));

        var resp6 = BuildResponse(passwordHash, state.MagicKey, state.JFinal);

        var resp96 = BuildResponse(cryptHash, state.MagicKey, state.JFinal);

        return new AuthResponse(resp6, resp96)
        {
            MagicKey = state.MagicKey,
            Depth = state.Depth,
            Table = state.Table,
            JFinal = state.JFinal
        };
    }

    internal static AuthResponse ComputeAuthResponse(string seed, string password)
    {
        return ComputeResponses(PrepareChallenge(seed), password);
    }

    // Builds a challenge exactly the way a real Yahoo server did, because a real client refuses anything else.
    // The 20-byte block the client decodes out of the seed is structured, not random: bytes 0-3 are the magic key
    // and bytes 4-19 are MD5(key || depth || table), which the client brute-forces back out to learn which
    // yahoo_fn.c transform to run on the key. The old version of this method emitted seeds random over the lookup
    // alphabets - a grammar this parser accepted but whose search never matches - and Messenger 5.x answers those
    // with EMPTY fields 6 and 96, failing every real-client login. We always encode depth 0 and table 0: depth 0
    // keeps yahoo_xfrm() an identity in every client lineage (its loop body never runs), and table 0 keeps the
    // loop-exit j at 1 so the SHA-1 length poke stays off - the one spot where the RE'd lineages disagree
    // (bitlbee pokes when j >= 3, jYMSG never does; at table 0 they and the real client all agree).
    internal static string MakeChallenge()
    {
        var comparison = new byte[ComparisonLength];

        RandomNumberGenerator.Fill(comparison.AsSpan(0, 4));

        // The searched preimage is key || depth as 16-bit little-endian || table - all zero bytes for our pair.
        var pair = new byte[7];

        Array.Copy(comparison, pair, 4);

        MD5.HashData(pair, comparison.AsSpan(4));

        // Phase-3 inverse: pack the ten 16-bit values the way the client's UTF-8-shaped decoder unpacks them.
        var packed = new List<byte>
        {
            // magic[0]: the decoder starts reading at index 1, so this byte only feeds the phase-2 stir.
            (byte)RandomNumberGenerator.GetInt32(256)
        };

        for (var i = 0; i < ComparisonLength; i += 2)
        {
            var value = (comparison[i] << 8) | comparison[i + 1];

            if (value < 0x80)
            {
                packed.Add((byte)value);
            }
            else if (value < 0x800)
            {
                packed.Add((byte)(0xC0 | (value >> 6)));
                packed.Add((byte)(0x80 | (value & 0x3F)));
            }
            else
            {
                packed.Add((byte)(0xE0 | (value >> 12)));
                packed.Add((byte)(0x80 | ((value >> 6) & 0x3F)));
                packed.Add((byte)(0x80 | (value & 0x3F)));
            }
        }

        // The decoder peeks one byte past each lead byte before using it, so when the final value packs into a
        // single byte it needs a spare byte to peek at. Always supplying one is harmless in every other case.
        packed.Add((byte)RandomNumberGenerator.GetInt32(256));

        // Phase-2 inverse, run forward: the client stirs magic[k] into (magic[k-1] * 0xcd) ^ magic[k] using the
        // raw values, so the raw stream falls out of the packed one in one pass.
        var raw = new byte[packed.Count];

        raw[0] = packed[0];

        for (var k = 1; k < raw.Length; k++)
        {
            raw[k] = (byte)(packed[k] ^ (byte)(raw[k - 1] * 0xcd));
        }

        // Phase-1 inverse: each byte becomes an operand character (high five bits) and an operator (low three).
        // The parentheses are decoration - every client parser skips them - but real seeds wore them to look like
        // arithmetic, so ours do too, and the string ends on a dangling operand the parser never folds.
        var builder = new StringBuilder();

        var open = 0;

        foreach (var b in raw)
        {
            if (open < 3 && RandomNumberGenerator.GetInt32(5) == 0)
            {
                builder.Append('(');

                open++;
            }

            builder.Append(ChallengeLookup[b >> 3]);

            if (open > 0 && RandomNumberGenerator.GetInt32(5) == 0)
            {
                builder.Append(')');

                open--;
            }

            builder.Append(OperandLookup[b & 7]);
        }

        builder.Append(ChallengeLookup[RandomNumberGenerator.GetInt32(ChallengeLookup.Length)]);

        while (open-- > 0)
        {
            builder.Append(')');
        }

        var candidate = builder.ToString();

        // The construction is deterministic, but nothing downstream can recover from a seed the two sides read
        // differently - so prove the whole round trip, including the embedded pair, before handing it out.
        var state = PrepareChallenge(candidate);

        if (state == null || state.Depth != 0 || state.Table != 0 || state.JFinal != 1)
        {
            return null;
        }

        return candidate;
    }

    // Phase 1: fold the seed into a byte per operator. Returns null on any character the reference cannot handle -
    // where it would spin forever, because it does not advance the read pointer on an unknown character.
    static List<byte> ParseSeedMagic(string seed)
    {
        var magic = new List<byte>();

        var magicWork = 0u;

        foreach (var c in seed)
        {
            if (c == '(' || c == ')')
            {
                continue;
            }

            if (IsAsciiAlpha(c) || IsAsciiDigit(c))
            {
                var index = ChallengeLookup.IndexOf(c);

                if (index < 0)
                {
                    return null;
                }

                magicWork = (uint)index << 3;

                continue;
            }

            var operand = OperandLookup.IndexOf(c);

            if (operand < 0)
            {
                return null;
            }

            if (magic.Count >= 64)
            {
                break;
            }

            magic.Add((byte)(magicWork | (uint)operand));
        }

        return magic;
    }

    // Phases 2 and 3: stir the parsed bytes, then decode them into the 20-byte comparison block.
    static byte[] BuildComparisonSource(List<byte> magic)
    {
        var magicLen = magic.Count;

        for (var cnt = magicLen - 2; cnt >= 0; cnt--)
        {
            var byte1 = magic[cnt];
            var byte2 = magic[cnt + 1];

            byte1 = (byte)(byte1 * 0xcd);
            byte1 ^= byte2;

            magic[cnt + 1] = byte1;
        }

        var comparison = new byte[ComparisonLength];

        var magicCnt = 1;
        var x = 0;

        do
        {
            uint bl;

            if (magicCnt >= magicLen)
            {
                break;
            }

            uint cl = magic[magicCnt++];

            if (magicCnt >= magicLen)
            {
                break;
            }

            if (cl > 0x7F)
            {
                if (cl < 0xe0)
                {
                    bl = cl = (cl & 0x1f) << 6;
                }
                else
                {
                    if (magicCnt >= magicLen)
                    {
                        break;
                    }

                    bl = magic[magicCnt++];
                    cl = (cl & 0x0f) << 6;
                    bl = ((bl & 0x3f) + cl) << 6;
                }

                if (magicCnt >= magicLen)
                {
                    break;
                }

                cl = magic[magicCnt++];
                bl = (cl & 0x3f) + bl;
            }
            else
            {
                bl = cl;
            }

            comparison[x++] = (byte)((bl & 0xff00) >> 8);
            comparison[x++] = (byte)(bl & 0xff);
        }
        while (x < ComparisonLength);

        // Anything short of a full block means the client and server would be comparing different garbage.
        return x < ComparisonLength ? null : comparison;
    }

    // The client's search for the transform pair. Returns the loop-exit value of j, which is one past the matched
    // index - that off-by-one is what the "j >= 3" test downstream actually reads.
    static (int Depth, int Table, int JFinal, bool Found) SearchTransformTable(byte[] magicKey, byte[] comparison)
    {
        var chal = new byte[7];

        Array.Copy(magicKey, chal, 4);

        var target = comparison.AsSpan(4, 16);

        Span<byte> digest = stackalloc byte[16];

        var searching = true;

        var i = 0;
        var j = 0;

        for (i = 0; i < 0xFFFF && searching; i++)
        {
            for (j = 0; j < 5 && searching; j++)
            {
                chal[4] = (byte)i;
                chal[5] = (byte)(i >> 8);
                chal[6] = (byte)j;

                MD5.HashData(chal, digest);

                if (digest.SequenceEqual(target))
                {
                    return (i, j, j + 1, true);
                }
            }
        }

        return (0, 0, j, false);
    }

    // The HMAC-shaped half: pad the hash with 0x36/0x5c, run it through SHA-1 twice, then spell the digest out
    // using the client's alphabets.
    static string BuildResponse(string hash, byte[] magicKey, int jFinal)
    {
        var hashBytes = Encoding.ASCII.GetBytes(hash);

        var xor1 = new byte[64];
        var xor2 = new byte[64];

        for (var x = 0; x < 64; x++)
        {
            xor1[x] = x < hashBytes.Length ? (byte)(hashBytes[x] ^ 0x36) : (byte)0x36;
            xor2[x] = x < hashBytes.Length ? (byte)(hashBytes[x] ^ 0x5c) : (byte)0x5c;
        }

        var ctx1 = new YmsgSha1();

        ctx1.Append(xor1);

        if (jFinal >= 3)
        {
            // Verbatim from the reference: it reaches into the SHA-1 context and rewrites the bit counter from 512
            // to 511 before the final 4 bytes go in, so the padded length is 543 bits and not 544. Nothing about
            // this is standard SHA-1; it is simply what the client does, so we do it too.
            ctx1.LengthLow = 0x1ff;
        }

        ctx1.Append(magicKey);

        var digest1 = ctx1.Finish();

        var ctx2 = new YmsgSha1();

        ctx2.Append(xor2);
        ctx2.Append(digest1);

        var digest2 = ctx2.Finish();

        var result = new StringBuilder();

        for (var x = 0; x < 20; x += 2)
        {
            var val = (uint)(digest2[x] << 8) + digest2[x + 1];

            var lookup = (val >> 0x0b) & 0x1f;

            if (lookup >= Alphabet1.Length)
            {
                break;
            }

            result.Append(Alphabet1[(int)lookup]);
            result.Append('=');

            lookup = (val >> 0x06) & 0x1f;

            if (lookup >= Alphabet2.Length)
            {
                break;
            }

            result.Append(Alphabet2[(int)lookup]);

            lookup = (val >> 0x01) & 0x1f;

            if (lookup >= Alphabet2.Length)
            {
                break;
            }

            result.Append(Alphabet2[(int)lookup]);

            lookup = val & 0x01;

            if (lookup >= DelimitLookup.Length)
            {
                break;
            }

            result.Append(DelimitLookup[(int)lookup]);
        }

        return result.ToString();
    }

    // base64 over the y64 alphabet, padded with '-' - see the Y64Alphabet comment.
    internal static string Y64(byte[] input)
    {
        var output = new StringBuilder();

        var i = 0;

        for (; input.Length - i >= 3; i += 3)
        {
            output.Append(Y64Alphabet[input[i] >> 2]);
            output.Append(Y64Alphabet[((input[i] << 4) & 0x30) | (input[i + 1] >> 4)]);
            output.Append(Y64Alphabet[((input[i + 1] << 2) & 0x3c) | (input[i + 2] >> 6)]);
            output.Append(Y64Alphabet[input[i + 2] & 0x3f]);
        }

        var remaining = input.Length - i;

        if (remaining > 0)
        {
            output.Append(Y64Alphabet[input[i] >> 2]);

            if (remaining > 1)
            {
                output.Append(Y64Alphabet[((input[i] << 4) & 0x30) | (input[i + 1] >> 4)]);
                output.Append(Y64Alphabet[(input[i + 1] << 2) & 0x3c]);
            }
            else
            {
                output.Append(Y64Alphabet[(input[i] << 4) & 0x30]);
                output.Append(Y64Pad);
            }

            output.Append(Y64Pad);
        }

        return output.ToString();
    }

    // MD5-crypt, the "$1$" scheme. Ported from bitlbee's protocols/yahoo/crypt.c, which is itself the classic
    // implementation - including the deliberately strange bit-driven loop and the 1000-round stretch.
    internal static string YahooCrypt(string key, string salt)
    {
        const string MagicPrefix = "$1$";

        const string B64T = "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

        if (salt.StartsWith(MagicPrefix, StringComparison.Ordinal))
        {
            salt = salt[MagicPrefix.Length..];
        }

        var dollar = salt.IndexOf('$');

        if (dollar >= 0)
        {
            salt = salt[..dollar];
        }

        if (salt.Length > 8)
        {
            salt = salt[..8];
        }

        var keyBytes = Encoding.UTF8.GetBytes(key);
        var saltBytes = Encoding.UTF8.GetBytes(salt);
        var prefixBytes = Encoding.ASCII.GetBytes(MagicPrefix);

        byte[] altResult;

        using (var alt = IncrementalHash.CreateHash(HashAlgorithmName.MD5))
        {
            alt.AppendData(keyBytes);
            alt.AppendData(saltBytes);
            alt.AppendData(keyBytes);

            altResult = alt.GetHashAndReset();
        }

        using (var ctx = IncrementalHash.CreateHash(HashAlgorithmName.MD5))
        {
            ctx.AppendData(keyBytes);
            ctx.AppendData(prefixBytes);
            ctx.AppendData(saltBytes);

            var cnt = keyBytes.Length;

            for (; cnt > 16; cnt -= 16)
            {
                ctx.AppendData(altResult, 0, 16);
            }

            ctx.AppendData(altResult, 0, cnt);

            // For every 1 bit in the key length a NUL goes in, for every 0 bit the key's first byte. The reference
            // calls this out as "not what was intended but we have to follow this to be compatible".
            var zero = new byte[] { 0 };
            var firstKeyByte = new[] { keyBytes.Length > 0 ? keyBytes[0] : (byte)0 };

            for (cnt = keyBytes.Length; cnt > 0; cnt >>= 1)
            {
                ctx.AppendData((cnt & 1) != 0 ? zero : firstKeyByte);
            }

            altResult = ctx.GetHashAndReset();
        }

        for (var cnt = 0; cnt < 1000; cnt++)
        {
            using var round = IncrementalHash.CreateHash(HashAlgorithmName.MD5);

            if ((cnt & 1) != 0)
            {
                round.AppendData(keyBytes);
            }
            else
            {
                round.AppendData(altResult);
            }

            if (cnt % 3 != 0)
            {
                round.AppendData(saltBytes);
            }

            if (cnt % 7 != 0)
            {
                round.AppendData(keyBytes);
            }

            if ((cnt & 1) != 0)
            {
                round.AppendData(altResult);
            }
            else
            {
                round.AppendData(keyBytes);
            }

            altResult = round.GetHashAndReset();
        }

        var buffer = new StringBuilder();

        buffer.Append(MagicPrefix);
        buffer.Append(salt);
        buffer.Append('$');

        void B64From24Bit(byte b2, byte b1, byte b0, int n)
        {
            var w = ((uint)b2 << 16) | ((uint)b1 << 8) | b0;

            while (n-- > 0)
            {
                buffer.Append(B64T[(int)(w & 0x3f)]);

                w >>= 6;
            }
        }

        B64From24Bit(altResult[0], altResult[6], altResult[12], 4);
        B64From24Bit(altResult[1], altResult[7], altResult[13], 4);
        B64From24Bit(altResult[2], altResult[8], altResult[14], 4);
        B64From24Bit(altResult[3], altResult[9], altResult[15], 4);
        B64From24Bit(altResult[4], altResult[10], altResult[5], 4);
        B64From24Bit(0, 0, altResult[11], 2);

        return buffer.ToString();
    }

    // RFC 3174 SHA-1 with the bit counter left writable, because the client rewrites it mid-stream. The framework
    // SHA1 cannot express that, which is the whole reason this exists.
    internal sealed class YmsgSha1
    {
        readonly uint[] hash = { 0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0 };

        readonly byte[] block = new byte[64];

        int blockIndex;

        internal uint LengthLow { get; set; }

        internal uint LengthHigh { get; set; }

        internal void Append(byte[] data)
        {
            foreach (var b in data)
            {
                block[blockIndex++] = b;

                LengthLow += 8;

                if (LengthLow == 0)
                {
                    LengthHigh++;
                }

                if (blockIndex == 64)
                {
                    ProcessBlock();
                }
            }
        }

        internal byte[] Finish()
        {
            Pad();

            var digest = new byte[20];

            for (var i = 0; i < 20; i++)
            {
                digest[i] = (byte)(hash[i >> 2] >> (8 * (3 - (i & 0x03))));
            }

            return digest;
        }

        void Pad()
        {
            if (blockIndex > 55)
            {
                block[blockIndex++] = 0x80;

                while (blockIndex < 64)
                {
                    block[blockIndex++] = 0;
                }

                ProcessBlock();

                while (blockIndex < 56)
                {
                    block[blockIndex++] = 0;
                }
            }
            else
            {
                block[blockIndex++] = 0x80;

                while (blockIndex < 56)
                {
                    block[blockIndex++] = 0;
                }
            }

            block[56] = (byte)(LengthHigh >> 24);
            block[57] = (byte)(LengthHigh >> 16);
            block[58] = (byte)(LengthHigh >> 8);
            block[59] = (byte)LengthHigh;
            block[60] = (byte)(LengthLow >> 24);
            block[61] = (byte)(LengthLow >> 16);
            block[62] = (byte)(LengthLow >> 8);
            block[63] = (byte)LengthLow;

            ProcessBlock();
        }

        void ProcessBlock()
        {
            uint[] k = { 0x5A827999, 0x6ED9EBA1, 0x8F1BBCDC, 0xCA62C1D6 };

            var w = new uint[80];

            for (var t = 0; t < 16; t++)
            {
                w[t] = (uint)(block[t * 4] << 24 | block[t * 4 + 1] << 16 | block[t * 4 + 2] << 8 | block[t * 4 + 3]);
            }

            for (var t = 16; t < 80; t++)
            {
                w[t] = RotateLeft(w[t - 3] ^ w[t - 8] ^ w[t - 14] ^ w[t - 16], 1);
            }

            var a = hash[0];
            var b = hash[1];
            var c = hash[2];
            var d = hash[3];
            var e = hash[4];

            for (var t = 0; t < 20; t++)
            {
                var temp = RotateLeft(a, 5) + ((b & c) | ((~b) & d)) + e + w[t] + k[0];

                e = d;
                d = c;
                c = RotateLeft(b, 30);
                b = a;
                a = temp;
            }

            for (var t = 20; t < 40; t++)
            {
                var temp = RotateLeft(a, 5) + (b ^ c ^ d) + e + w[t] + k[1];

                e = d;
                d = c;
                c = RotateLeft(b, 30);
                b = a;
                a = temp;
            }

            for (var t = 40; t < 60; t++)
            {
                var temp = RotateLeft(a, 5) + ((b & c) | (b & d) | (c & d)) + e + w[t] + k[2];

                e = d;
                d = c;
                c = RotateLeft(b, 30);
                b = a;
                a = temp;
            }

            for (var t = 60; t < 80; t++)
            {
                var temp = RotateLeft(a, 5) + (b ^ c ^ d) + e + w[t] + k[3];

                e = d;
                d = c;
                c = RotateLeft(b, 30);
                b = a;
                a = temp;
            }

            hash[0] += a;
            hash[1] += b;
            hash[2] += c;
            hash[3] += d;
            hash[4] += e;

            blockIndex = 0;
        }

        static uint RotateLeft(uint value, int bits) => (value << bits) | (value >> (32 - bits));
    }

    static bool IsAsciiAlpha(char c) => (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');

    static bool IsAsciiDigit(char c) => c >= '0' && c <= '9';
}
